### ISSUE TITLE
Use "-all1" option will test the fxx_mulAdd, which is not a unary function

### ISSUE THREAD

**Issue by RolfyYu** [ucb-bar/berkeley-testfloat-3#7]
In "testfloat.c": 
line 1683~1686, fxx_mulAdd is not labeled as "FUNC_ARG_BINARY", 
so the code logic will put fxx_mulAdd into all1 list.

**Comment by jhauser-ucberkeley** [comment]
You're absolutely right about the bug, though not about the correct fix, since the multiply-add functions aren't binary either.

This was made to work properly in `testsoftfloat` a long time ago, but I evidently forgot to upgrade `testfloat` at the same time.  As it happens, I'm already working on the next release (3e).  I'll include the correction for this issue in that realease.

**Comment by jhauser-ucberkeley** [comment]
This mistake is believed to be fixed in Release 3e.

**Comment by RolfyYu** [comment]
confirm that -all1 option is fixed.
